FROM ubuntu:22.04

RUN apk update \
    && apk add --no-cache \
    apache2 \
    php-apache2 \
    php \
    php-bcmath \
    php-curl \
    php-intl \
    php-json \
    php-mbstring \
    php-xml \
    php-zip
